# Generated by Django 3.0.3 on 2020-05-19 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recruit', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='application_hit',
        ),
    ]
