# Generated by Django 3.0.3 on 2020-05-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruit', '0002_delete_application_hit'),
    ]

    operations = [
        migrations.CreateModel(
            name='application_hit',
            fields=[
                ('application_id', models.IntegerField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=20)),
                ('post_id', models.IntegerField()),
                ('post_name', models.CharField(max_length=40)),
                ('application_date', models.DateField()),
            ],
            options={
                'db_table': 'application_hit',
            },
        ),
    ]
