# Generated by Django 3.0.3 on 2020-05-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruit', '0003_application_hit'),
    ]

    operations = [
        migrations.CreateModel(
            name='posts',
            fields=[
                ('post_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'posts',
            },
        ),
    ]
