# Generated by Django 3.0.3 on 2020-05-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruit', '0004_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='notice',
            fields=[
                ('notice_head', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('notice_data', models.CharField(max_length=300)),
                ('ndate', models.DateField()),
            ],
            options={
                'db_table': 'notice',
            },
        ),
    ]
